
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  timeout: 5000
  
  # username: postgres
  # password: 
  # host: db

development:
  <<: *default
  database: VueCMS_development

test:
  <<: *default
  database: VueCMS_test

production:
  <<: *default
  database: VueCMS_production
  username: VueCMS
  password: <%= ENV['VUECMS_DATABASE_PASSWORD'] %>
